### ISSUE TITLE
Fix Segments

### ISSUE THREAD

**Issue by kirilklein** [mikkelfo/ehr2vec#42]
Incorrect segments are produced on azure, e.g. 1,1,1,2,3,4,5,1,1

**Comment by mikkelfo** [comment]
This might not be incorrect and simply just be the data (atleast on CR)

If you look at admission IDs, they can have AAA B C D E A A. Can you check their admission ids and see if it is a bug? @kirilklein

**Comment by kirilklein** [comment]
Yes, one reason for that might be that some timestamps are set to 1800 for example (for diagnoses that were already present) they are then pushed to the beginning of the sequence since we sort by timestamps. It's not clear whether that's ideal, but let's keep it for now @mikkelfo
